### ISSUE TITLE
Calling details page increments invocation counter for flow

### ISSUE THREAD

**Issue by pasdam** [faasflow/faas-flow-tower#24]
Every time the flow detail page is reloaded the invocation counter is increased, whereas it should only report real invocations

**Comment by s8sg** [comment]
We will use the requests count, to get there requests  
```go
requests, err := listFlowRequests(flowName)
	if err != nil {
		log.Printf("failed to get requests, error: %v", err)
		requests = make(map[string]string)
	}
```
On success it returns a map, we can just use the Len 
For error case we can just use `0`

**Comment by s8sg** [comment]
Fixed in: https://github.com/faasflow/faas-flow-tower/commit/8640e33b3013a8e681dbc129190ccb861159289d
